apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment
  labels:
    app: demo-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      imagePullSecrets:
        - name: regcred  # This should be at the spec level

      containers:
        - name: demo-app
          image: quadrefolio/demo-app:1719127512-a208f391
          
          ports:
            - containerPort: 80  # Move inside container definition

          livenessProbe:
            httpGet:
              path: /live
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /read
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
