apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment 
  labels:
    app: demo-app 
spec:
  replicas: 5
  selector:
    matchLabels:
      app: demo-app 
  template:
    metadata:
      labels:
        app: demo-app 
    spec:
      containers:
        - name: demo-app 
          image: quadrefolio/demo-app:latest 
      imagePullSecrets:
        - name: regcred
          ports:
            - containerPort: 80 
          livenessProbe:
            httpGet:
              path: /live 
              port: 80 
              initialDelaySeconds: 5
              periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /read
              port: 80 
              initialDelaySeconds: 5
              periodSeconds: 10
