apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment 
  labels:
    app: demo-app 
spec:
  replicas: 5
  selector:
    matchLabels:
      app: demo-app 
  template:
    metadata:
      labels:
        app: demo-app 
    spec:
      containers:
        - name: demo-app 
          image: quadrefolio/demo-app:1776686362-026b9d65
          ports:
            - containerPort: 8080 
          livenessProbe:
            httpGet:
              path: /live 
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /read
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
      imagePullSecrets:
        - name: regcred
