apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment # Changed name to reflect your application
  labels:
    app: demo-app # Changed label to reflect your application
spec:
  replicas: 5
  selector:
    matchLabels:
      app: demo-app # Changed label to reflect your application
  template:
    metadata:
      labels:
        app: demo-app # Changed label to reflect your application
    spec:
      containers:
        - name: demo-app # Changed container name to reflect your application
          image: quadrefolio/demo-app:latest # Your application image
          ports:
            - containerPort: 80 # Or the port your application uses
          livenessProbe:
            httpGet:
              path: /live # Adjust path to your application's liveness endpoint
              port: 80 # Or the port your application uses
              initialDelaySeconds: 5
              periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /read # Adjust path to your application's readiness endpoint
              port: 80 # Or the port your application uses
              initialDelaySeconds: 5
              periodSeconds: 10
      #volumes section was removed as it was referring to nginx config map.