apiVersion: v1
kind: Service
metadata:
  name: demo-app-service # Changed service name to reflect your application
  labels:
    app: demo-app # Changed label to match your application
spec:
  selector:
    app: demo-app # Changed selector to match your application
  ports:
    - protocol: TCP
      port: 80 # The service's port
      targetPort: 80 # The container's port
  type: ClusterIP